### ISSUE TITLE
[Security] Workflow continuous-delivery.yml is using vulnerable action JamesIves/github-pages-deploy-action

### ISSUE THREAD

**Issue by Ale0x78** [Alex-D/Column-View#1]
The workflow continuous-delivery.yml is referencing action JamesIves/github-pages-deploy-action using references 3.5.7. However this reference is missing the commit [661e33871bce8107c9af083f7415176608dce40e](https://github.com/JamesIves/github-pages-deploy-action/commits/661e33871bce8107c9af083f7415176608dce40e) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by Alex-D** [comment]
Thank you for the report :)
